"""HealthFlow Domain Layer.

Core business concepts, port interfaces, value objects, and transition rules.
This layer has ZERO external framework dependencies.

Ref: docs/architecture/ARCHITECTURE.md §2.4, §4.4
"""

from healthflow_domain.entities import (
    AuditRecord,
    AuthorizationCase,
    EscalationRecord,
    InsurancePlan,
    Patient,
    SubmissionRecord,
    VerificationRecord,
    WorkflowTransition,
)
from healthflow_domain.enums import (
    AuditEventType,
    CasePriority,
    EscalationReason,
    ProcedureType,
    VerificationStatus,
    WorkflowState,
)
from healthflow_domain.exceptions import (
    DataBoundaryViolationError,
    DomainError,
    DomainValidationError,
    EntityNotFoundError,
    InvalidWorkflowTransitionError,
    InvariantViolationError,
)
from healthflow_domain.external_models import (
    DocumentContent,
    DocumentMetadata,
    EhrPatientRecord,
    ExternalVerificationResult,
    PayerCoverageRecord,
    PortalStatusRecord,
    PortalSubmissionAck,
    PortalSubmissionPayload,
    ProcedureRequirements,
)
from healthflow_domain.identifiers import (
    AuditId,
    CaseId,
    EscalationId,
    PatientId,
    PlanId,
    SubmissionId,
    TransitionId,
    VerificationId,
)
from healthflow_domain.ports import (
    AuditRepository,
    AuthorizationCaseRepository,
    AuthorizationGatewayPort,
    AuthorizationStatusGatewayPort,
    DocumentStorePort,
    EhrPort,
    EscalationRepository,
    InsurancePlanRepository,
    PatientRepository,
    PayerPort,
    SubmissionRepository,
    UnitOfWork,
    VerificationProviderPort,
    VerificationRepository,
    WorkflowStateRepository,
)
from healthflow_domain.workflow_state import (
    ALLOWED_TRANSITIONS,
    is_transition_allowed,
    validate_workflow_transition,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "AuditEventType",
    "AuditId",
    "AuditRecord",
    "AuditRepository",
    "AuthorizationCase",
    "AuthorizationCaseRepository",
    "AuthorizationGatewayPort",
    "AuthorizationStatusGatewayPort",
    "CaseId",
    "CasePriority",
    "DataBoundaryViolationError",
    "DocumentContent",
    "DocumentMetadata",
    "DocumentStorePort",
    "DomainError",
    "DomainValidationError",
    "EhrPatientRecord",
    "EhrPort",
    "EntityNotFoundError",
    "EscalationId",
    "EscalationReason",
    "EscalationRecord",
    "EscalationRepository",
    "ExternalVerificationResult",
    "InsurancePlan",
    "InsurancePlanRepository",
    "InvalidWorkflowTransitionError",
    "InvariantViolationError",
    "Patient",
    "PatientId",
    "PatientRepository",
    "PayerCoverageRecord",
    "PayerPort",
    "PlanId",
    "PortalStatusRecord",
    "PortalSubmissionAck",
    "PortalSubmissionPayload",
    "ProcedureRequirements",
    "ProcedureType",
    "SubmissionId",
    "SubmissionRecord",
    "SubmissionRepository",
    "TransitionId",
    "UnitOfWork",
    "VerificationId",
    "VerificationProviderPort",
    "VerificationRecord",
    "VerificationRepository",
    "VerificationStatus",
    "WorkflowState",
    "WorkflowStateRepository",
    "WorkflowTransition",
    "is_transition_allowed",
    "validate_workflow_transition",
]
