"""Phase 2 domain schema

Revision ID: afe115fba059
Revises:
Create Date: 2026-08-28 22:34:15.305728

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afe115fba059"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name_reference", sa.String(length=255), nullable=False),
        sa.Column("ehr_reference", sa.String(length=255), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patients_ehr_reference"), "patients", ["ehr_reference"], unique=True
    )
    op.create_table(
        "insurance_plans",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("patient_id", sa.String(length=64), nullable=False),
        sa.Column("insurer_reference", sa.String(length=255), nullable=False),
        sa.Column("plan_type", sa.String(length=100), nullable=False),
        sa.Column("member_reference", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_insurance_plans_insurer_reference"),
        "insurance_plans",
        ["insurer_reference"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insurance_plans_patient_id"),
        "insurance_plans",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "authorization_cases",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("patient_id", sa.String(length=64), nullable=False),
        sa.Column("insurance_plan_id", sa.String(length=64), nullable=False),
        sa.Column("procedure_type", sa.String(length=100), nullable=False),
        sa.Column("clinical_indication", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=50), nullable=False),
        sa.Column("current_state", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["insurance_plan_id"], ["insurance_plans.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_cases_patient_state",
        "authorization_cases",
        ["patient_id", "current_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authorization_cases_created_at"),
        "authorization_cases",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authorization_cases_current_state"),
        "authorization_cases",
        ["current_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authorization_cases_insurance_plan_id"),
        "authorization_cases",
        ["insurance_plan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authorization_cases_patient_id"),
        "authorization_cases",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "audit_records",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["authorization_cases.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audits_case_date", "audit_records", ["case_id", "timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_case_id"), "audit_records", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_event_type"),
        "audit_records",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_records_timestamp"), "audit_records", ["timestamp"], unique=False
    )
    op.create_table(
        "escalation_records",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("from_state", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"], ["authorization_cases.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_escalation_records_case_id"),
        "escalation_records",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_escalation_records_escalated_at"),
        "escalation_records",
        ["escalated_at"],
        unique=False,
    )
    op.create_table(
        "submission_records",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("submission_reference", sa.String(length=255), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("initial_status", sa.String(length=100), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["authorization_cases.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submission_records_case_id"),
        "submission_records",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submission_records_submission_reference"),
        "submission_records",
        ["submission_reference"],
        unique=True,
    )
    op.create_table(
        "verification_records",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("submission_reference", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("verification_details", sa.Text(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["authorization_cases.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_records_case_id"),
        "verification_records",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_records_submission_reference"),
        "verification_records",
        ["submission_reference"],
        unique=False,
    )
    op.create_table(
        "workflow_transitions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("from_state", sa.String(length=50), nullable=False),
        sa.Column("to_state", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("transitioned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["authorization_cases.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_transitions_case_date",
        "workflow_transitions",
        ["case_id", "transitioned_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_transitions_case_id"),
        "workflow_transitions",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_transitions_transitioned_at"),
        "workflow_transitions",
        ["transitioned_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workflow_transitions_transitioned_at"),
        table_name="workflow_transitions",
    )
    op.drop_index(
        op.f("ix_workflow_transitions_case_id"), table_name="workflow_transitions"
    )
    op.drop_index("idx_transitions_case_date", table_name="workflow_transitions")
    op.drop_table("workflow_transitions")
    op.drop_index(
        op.f("ix_verification_records_submission_reference"),
        table_name="verification_records",
    )
    op.drop_index(
        op.f("ix_verification_records_case_id"), table_name="verification_records"
    )
    op.drop_table("verification_records")
    op.drop_index(
        op.f("ix_submission_records_submission_reference"),
        table_name="submission_records",
    )
    op.drop_index(
        op.f("ix_submission_records_case_id"), table_name="submission_records"
    )
    op.drop_table("submission_records")
    op.drop_index(
        op.f("ix_escalation_records_escalated_at"), table_name="escalation_records"
    )
    op.drop_index(
        op.f("ix_escalation_records_case_id"), table_name="escalation_records"
    )
    op.drop_table("escalation_records")
    op.drop_index(op.f("ix_audit_records_timestamp"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_event_type"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_case_id"), table_name="audit_records")
    op.drop_index("idx_audits_case_date", table_name="audit_records")
    op.drop_table("audit_records")
    op.drop_index(
        op.f("ix_authorization_cases_patient_id"), table_name="authorization_cases"
    )
    op.drop_index(
        op.f("ix_authorization_cases_insurance_plan_id"),
        table_name="authorization_cases",
    )
    op.drop_index(
        op.f("ix_authorization_cases_current_state"), table_name="authorization_cases"
    )
    op.drop_index(
        op.f("ix_authorization_cases_created_at"), table_name="authorization_cases"
    )
    op.drop_index("idx_cases_patient_state", table_name="authorization_cases")
    op.drop_table("authorization_cases")
    op.drop_index(op.f("ix_insurance_plans_patient_id"), table_name="insurance_plans")
    op.drop_index(
        op.f("ix_insurance_plans_insurer_reference"), table_name="insurance_plans"
    )
    op.drop_table("insurance_plans")
    op.drop_index(op.f("ix_patients_ehr_reference"), table_name="patients")
    op.drop_table("patients")
    # ### end Alembic commands ###
